# Generated by Django 3.2.13 on 2022-09-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='location',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='career',
            name='type',
            field=models.CharField(default='TBD', max_length=255),
        ),
    ]
